version: "3.9"

services:
  app:
    build:
      context: .
      target: final
      dockerfile: DockerfileApp
    pull_policy: never
    container_name: pointservice
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - env/.env
    ports:
      - "1323:1323"
    networks:
      - pointservice-network
  scheduler:
    build:
      context: .
      target: scheduler-final
      dockerfile: DockerfileBatch
    pull_policy: never
    container_name: pointscheduler
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - env/.env
    ports:
      - "1324:1324"
    networks:
      - pointservice-network
  worker:
    build:
      context: .
      target: worker-final
      dockerfile: DockerfileBatch
    pull_policy: never
    container_name: pointworker
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - env/.env
    ports:
      - "1325:1325"
    networks:
      - pointservice-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pointservice-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pointservice-network
volumes:
  mysql-data:

networks:
  pointservice-network:
    driver: bridge
